language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "cp target/travis/settings.xml ~/.m2/settings.xml"

install: mvn install -DskipTests=true

# whitelist
branches:
  only:
    - master

script: mvn verify

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - mvn site --settings target/travis/settings.xml

env:
  global:
    secure: Jjjcy3kHNMRWFBS5ePAnslbyqtoNdByOGyW4TD8wsuotQ/2lg0Yg8WulwoZATu0taTinhMDuMR/WR2S6t53hDvK776EonNjj6/yGOG3tuCIn5Nas4Py3OBt6Mv8hxe6DBOdWqYLZzNSJXlaWN+XFd1CtDE8pKGmIZveGgH84ZwI=
