language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
install: mvn install -DskipTests=true
script: mvn verify
env:
  global:
    secure: Jjjcy3kHNMRWFBS5ePAnslbyqtoNdByOGyW4TD8wsuotQ/2lg0Yg8WulwoZATu0taTinhMDuMR/WR2S6t53hDvK776EonNjj6/yGOG3tuCIn5Nas4Py3OBt6Mv8hxe6DBOdWqYLZzNSJXlaWN+XFd1CtDE8pKGmIZveGgH84ZwI=
